NewApogyWebSite/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewApogyWebSite.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult AboutUs()
        {
            ViewBag.Title = "About Apogy";

            return View();
        }
        public ActionResult Platform()
        {
            ViewBag.Title = "Platform";

            return View();
        }
        public ActionResult Security()
        {
            ViewBag.Title = "Security";

            return View();
        }
        public ActionResult Service()
        {
            ViewBag.Title = "Service";

            return View();
        }
        public ActionResult Support()
        {
            ViewBag.Title = "Support";

            return View();
        }
        public ActionResult Training()
        {
            ViewBag.Title = "Training";

            return View();
        }
        //public ActionResult Awards()
        //{
        //    ViewBag.Title = "Awards";

        //    return View();
        //}
    }
}

NewApogyWebSite/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewApogyWebSite.Controllers
{
    public class LoginController: Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Log In";

            return View();
        }
    }
}

NewApogyWebSite/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewApogyWebSite.Controllers
{
    public class PrivacyController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Privacy Policy";

            return View();
        }
    }
}

NewApogyWebSite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewApogyWebSite.Controllers
{
    public class ProductsController : Controller
    {
        public ActionResult Apogy()
        {
            ViewBag.Title = "Apogy";

            return View();
        }
        public ActionResult ApogyEvents()
        {
            ViewBag.Title = "Apogy Events";

            return View();
        }
        public ActionResult Podium()
        {
            ViewBag.Title = "Podium";

            return View();
        }
    }
}

NewApogyWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon -->
    <!-- Web Fonts -->
    <link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>
    @Styles.Render("~/stylesheets/bundle2")
    @Styles.Render("~/stylesheets/bundle")
</head>
<body class="header-fixed">
<div class="wrapper">
    <!--=== Header v6 ===-->
    <div class="header-v6 header-dark-transparent header-sticky">
        <!-- Navbar -->
        <div class="navbar mega-menu" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="menu-container">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Navbar Brand -->
                    <div class="navbar-brand">
                        <a href="@Url.Action("Index", "Home")">
                            <img class="default-logo" src="~/Content/assets/images/logo.png" alt="Logo">
                            <img class="shrink-logo" src="~/Content/assets/images/logo-dark.png" alt="Logo">
                        </a>
                    </div>
                    <!-- ENd Navbar Brand -->
                    @*<!-- Header Inner Right -->
                <div class="header-inner-right">
                    <ul class="menu-icons-list">
                        <li class="menu-icons shopping-cart">
                            <i class="menu-icons-style radius-x fa fa-shopping-cart"></i>
                            <span class="badge">0</span>
                            <div class="shopping-cart-open">
                                <span class="shc-title">No products in the Cart</span>
                                <button type="button" class="btn-u"><i class="fa fa-shopping-cart"></i> Cart</button>
                                <span class="shc-total">Total: <strong>$0.00</strong></span>
                            </div>
                        </li>
                        <li class="menu-icons">
                            <i class="menu-icons-style search search-close search-btn fa fa-search"></i>
                            <div class="search-open">
                                <input type="text" class="animated fadeIn form-control" placeholder="Start searching ...">
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- End Header Inner Right -->*@
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-responsive-collapse">
                    <div class="menu-container">
                        <ul class="nav navbar-nav">
                            <!-- Home -->
                            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <!-- End Home -->
                            <!-- Solutions -->
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                    Solutions
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("CommercialEnablement", "Solutions")">Commercial Enablement</a></li>
                                    <li><a href="@Url.Action("Onboarding", "Solutions")">Onboarding</a></li>
                                    <li><a href="@Url.Action("ProductRealignment", "Solutions")">Product Realignment</a></li>
                                    <li><a href="@Url.Action("RegionalTraining", "Solutions")">Regional Training</a></li>
                                    <li><a href="@Url.Action("SalesKickoffs", "Solutions")">Sales Kickoffs</a></li>
                                    <li><a href="@Url.Action("PlanOfActionMeetings", "Solutions")">Plan of Action Meetings</a></li>
                                    <li><a href="@Url.Action("SpeakerPrograms", "Solutions")">Speaker Programs</a></li>
                                    <li><a href="@Url.Action("ClassroomTraining", "Solutions")">Classroom Training</a></li>
                                    <li><a href="@Url.Action("CoachingCommunication", "Solutions")">Coaching Communication</a></li>
                                    <li><a href="@Url.Action("ContentDelivery", "Solutions")">Content Delivery</a></li>
                                    <li><a href="@Url.Action("FieldLearning", "Solutions")">Field Learning</a></li>
                                    <li><a href="@Url.Action("MobileWorkforce", "Solutions")">Mobile Workforce</a></li>
                                    <li><a href="@Url.Action("EventEnablement", "Solutions")">Event Enablement</a></li>
                                </ul>
                            </li>
                            <!-- End Solution -->
                            <!-- Products -->
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                    Products
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Apogy", "Products")">Apogy</a></li>
                                    <li><a href="@Url.Action("ApogyEvents", "Products")">Apogy Events</a></li>
                                    <li><a href="@Url.Action("Podium", "Products")">Podium</a></li>
                                </ul>
                            </li>
                            <!-- End Products -->
                            <!-- Support -->
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                    Support
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Service", "About")">Implementation</a></li>
                                    <li><a href="@Url.Action("Support", "About")">Helpdesk</a></li>
                                    <li><a href="@Url.Action("Training", "About")">Training</a></li>
                                    <li><a href="@Url.Action("Security", "About")">Security</a></li>
                                    <li><a href="@Url.Action("Platform", "About")">Platform</a></li>
                                </ul>
                            </li>
                            <!-- End Support -->
                            <!-- About -->
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                    About
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("AboutUs", "About")">About Apogy</a></li>
                                    <li><a href="@Url.Action("Index", "Blog")">Blog</a></li>
                                    <li><a href="@Url.Action("Index", "Contact")">Contact Us</a></li>
                                </ul>
                            </li>
                            <!-- End About -->
                            <!-- LogIn -->
                            <li><a href="@Url.Action("Index", "Login")">LogIn</a></li>
                            <!-- End LogIn -->

                        </ul>
                    </div>
                </div><!--/navbar-collapse-->
            </div>
        </div>
        <!-- End Navbar -->
    </div>
    <!--=== End Header v6 ===-->
</div>
        
@RenderBody()
        
<!--=== Footer v6 ===-->
<div id="footer-v6" class="footer-v6">
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- About Us -->
                <div class="col-md-3 sm-margin-bottom-40 normalP">
                    <div class="heading-footer"><h2>About Apogy</h2></div>
                    <p>Apogy unifies all aspects of the commercial workflow to accelerate individual contribution and power organizational performance. We make remote teams more effective by keeping them mobile, connected, and informed.</p>
                </div>
                <!-- End About Us -->

                <!-- Recent News -->
                <div class="col-md-3 sm-margin-bottom-40">
                    <div class="heading-footer"><h2>Recent Blogs</h2></div>
                    <ul class="list-unstyled link-news">
                        <li>
                            <a href="@Url.Action("HateMobileApps", "Blog")">Three Reasons Why I Hate Mobile Apps</a>
                            <small>April 10, 2017</small>
                        </li>
                        <li>
                            <a href="@Url.Action("Millennial", "Blog")">Why 99% of Millennial Employees Want to Divorce Their LMS</a>
                            <small>February 22, 2017</small>
                        </li>
                        <li>
                            <a href="@Url.Action("SocialLearning", "Blog")">Where Social Learning Fails</a>
                            <small>February 6, 2017</small>
                        </li>
                    </ul>
                </div>
                <!-- End Recent News -->

                <!-- Useful Links -->
                <div class="col-md-3 sm-margin-bottom-40">
                    <div class="heading-footer"><h2>Useful Links</h2></div>
                    <ul class="list-unstyled footer-link-list">
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="@Url.Action("Apogy", "Products")">Apogy</a></li>
                        <li><a href="@Url.Action("ApogyEvents", "Products")">Apogy Events</a></li>
                        <li><a href="@Url.Action("Podium", "Products")">Podium</a></li>
                        <li><a href="@Url.Action("Index", "Contact")">Contact Us</a></li>
                    </ul>
                </div>
                <!-- End Useful Links -->

                <!-- Contacts -->
                <div class="col-md-3">
                    <div class="heading-footer"><h2>Contacts</h2></div>
                    <ul class="list-unstyled contacts">
                        <li>
                            <i class="radius-3x fa fa-map-marker"></i>
                            379 West Broadway,
                            New York, NY 10012
                        </li>
                        <li>
                            <i class="radius-3x fa fa-globe"></i>
                            <a href="@Url.Action("Index", "Contact")">info@apogy.com</a><br>
                            <a href="https://www.apogy.com">www.apogy.com</a>
                        </li>
                    </ul>
                </div>
                <!-- End Contacts -->
            </div>
        </div><!--/container -->
    </div>

    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-8 sm-margon-bottom-10">
                    <ul class="list-inline terms-menu">
                        <li class="silver">Copyright © 2017 - All Rights Reserved</li>
                        <li><a href="@Url.Action("Index", "Privacy")">Privacy and Policy</a></li>
                        <li><a href="@Url.Action("Support", "About")">Support</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline dark-social pull-right space-bottom-0">
                        <li>
                            <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Facebook" href="https://www.facebook.com/apogy/">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a data-placement="top" data-toggle="tooltip" class="tooltips" data-original-title="Twitter" href="https://twitter.com/apogyapp">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--=== End Footer v6 ===-->
<!--[if lt IE 9]>
    <script src="~/Content/assets/plugins/respond.js"></script>
    <script src="~/Content/assets/plugins/html5shiv.js"></script>
    <script src="~/Content/assets/plugins/placeholder-IE-fixes.js"></script>
<![endif]-->
@Scripts.Render("~/jquery/bundle")
@Scripts.Render("~/javascript/bundle")
@RenderSection("PageScripts", required: false)
</body>
</html>